### PR TITLE
added rem|vw|vh|vmin|max to CSS units detection

### PR DESCRIPTION
**Pull request by FireCoding**
See #28

### CODE REVIEW

**Comment by FireCoding** [comment]
Have you inspected my PR yet?

Looking forward to the next update...

**Comment by kstenschke** [comment]
Hi and thank you for the PR!  👍 :-)
i am a little short on time currently. As soon as i have a chance i'll issue the next update, most probably including your PR (looks good from the first look at it).

Greetings, Kay

**Comment by FireCoding** [comment]
Hi, just curious - are you planning a new release anytime soon by chance?

**Comment by kstenschke** [comment]
Hey David, 
as i am lacking the time for large Shifter features, i reverted started but unfinished major new features for now, and released 1.4.0, including your addition (with a little bugfix). Thanks again for your contribution. If you let me know your full name and would like that, i'll add you to the contributors list.

**Comment by FireCoding** [comment]
Thanks!  Love the new release!  Sorry about the bugfix.  --Joshua David

**Comment by kstenschke** [comment]
You're welcome 👍

**Pull request merged**
