### PR TITLE
Fixed NPE on initialization,...

### PR DESCRIPTION
**Pull request by krasa**
set background for restoreSettings, removed useless ApplicationComponent

### CODE REVIEW

**Comment by kstenschke** [comment]
Thank you Vojtěch

**Comment by krasa** [comment]
No problem. But how did you even managed to set <font swing-font="OptionPane.messageFont"/>? I don't have that font in the Select Font dialog (win 10).

**Comment by kstenschke** [comment]
See attached screenshot, it's in the "swing fonts" tab of the font selection dialog (Mac OS).

optionpane-messagefont

**Comment by krasa** [comment]
Well, that explains it. 
image


I'll report some bug to JetBrains, it should not fail at runtime if you don't have that font.

**Comment by kstenschke** [comment]
Yes, one would expect the GUI options to be cross-platform compatible.
Thanks for checking back and reporting 👍

**Pull request merged**
